# Generated by Django 3.2.24 on 2024-02-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240224_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_activation',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
