# Generated by Django 3.2.24 on 2024-03-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_dashboard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='bordDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
