# Generated by Django 3.2.24 on 2024-03-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_dashboard_borddescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='user',
        ),
    ]
