# Generated by Django 3.2.24 on 2024-03-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_dashboard_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('indexColor', models.CharField(max_length=20)),
                ('indexNumber', models.IntegerField()),
                ('defaultTaskCategory', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='dashboard',
            name='task_Categorie',
            field=models.ManyToManyField(to='core.TaskCategorie'),
        ),
    ]
