# Generated by Django 3.2.25 on 2024-03-14 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_mediafile_task_taskcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='creator',
        ),
    ]
