# Generated by Django 3.2.25 on 2024-03-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='files_list',
            field=models.ManyToManyField(to='core.MediaFile'),
        ),
    ]
