# Generated by Django 3.2.25 on 2024-03-28 11:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_task_files_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='files_list',
        ),
        migrations.AddField(
            model_name='task',
            name='task_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.task_image_file_path),
        ),
    ]
