# Generated by Django 3.2.25 on 2024-03-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20240328_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_file',
        ),
        migrations.AddField(
            model_name='task',
            name='files_list',
            field=models.ManyToManyField(to='core.MediaFile'),
        ),
    ]
