# Generated by Django 3.2.25 on 2024-03-28 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20240328_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='files_list',
        ),
        migrations.AddField(
            model_name='mediafile',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.task'),
        ),
    ]
