# Generated by Django 3.2.25 on 2024-04-01 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20240328_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='task_Categorie',
        ),
        migrations.RemoveField(
            model_name='task',
            name='taskComments',
        ),
        migrations.AddField(
            model_name='taskcategorie',
            name='dashboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.dashboard'),
        ),
    ]
