# Generated by Django 3.2.25 on 2024-04-10 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_task_dashboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='dashboard',
        ),
        migrations.AddField(
            model_name='task',
            name='taskCategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.dashboard'),
        ),
    ]
