# Generated by Django 3.2.25 on 2024-04-11 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20240410_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskCategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.taskcategorie'),
        ),
    ]
