# Generated by Django 3.2.25 on 2024-04-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_task_taskcategorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcategorie',
            name='indexNumber',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
    ]
