# Generated by Django 3.2.25 on 2024-04-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_taskcategorie_indexnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcategorie',
            name='indexColor',
            field=models.CharField(max_length=200),
        ),
    ]
