# Generated by Django 3.2.25 on 2024-04-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20240430_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='taskcategorie',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
