# Generated by Django 3.2.25 on 2024-05-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20240430_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcategorie',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
