# Generated by Django 3.2.25 on 2024-05-30 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20240527_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assign_To',
        ),
        migrations.AddField(
            model_name='task',
            name='assign_To',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigner', to=settings.AUTH_USER_MODEL),
        ),
    ]
