# Generated by Django 3.2.25 on 2026-08-16 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20240530_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TaskReminderLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('not_started', 'Not started reminder'), ('mid_term', 'Mid-term reminder'), ('near_deadline', 'Near-deadline reminder'), ('overdue', 'Overdue notification')], max_length=32)),
                ('assignment_cycle_started_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='core.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='taskreminderlog',
            index=models.Index(fields=['task', 'user', 'phase'], name='core_taskre_task_id_5294c4_idx'),
        ),
        migrations.AddIndex(
            model_name='taskreminderlog',
            index=models.Index(fields=['sent_at'], name='core_taskre_sent_at_07587c_idx'),
        ),
    ]
